package com.jashawn.inventory_api.Exceptions;

public enum ErrorCode {
    BUSINESS_RULE_VIOLATION,
    DUPLICATE_RESOURCE_VIOLATION,
    INACTIVE_RESOURCE_VIOLATION,
    INVALID_FIELD_VIOLATION,
    RESOURCE_NOT_FOUND_VIOLATION,
    INVALID_STATE_VIOLATION,
    INSUFFICIENT_AVAILABLE_STOCK,
    INSUFFICIENT_STOCK,
    INVALID_STOCK_MOVEMENT
}
